# Server
server.port=8081

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ripple_db
spring.datasource.username=sreejapaluri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=WARN
logging.level.com.ripple=DEBUG
logging.level.org.springframework=WARN

