# Server
server.port=8081
user.service.url=http://localhost:8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ripple_db
spring.datasource.username=sreejapaluri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Logging
logging.level.org.hibernate.SQL=WARN
logging.level.com.ripple=DEBUG
logging.level.org.springframework=WARN

#Redis
spring.data.redis.host = localhost
spring.data.redis.port = 6379
spring.data.redis.timeout=1000ms

#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.jackson.serialization.write-dates-as-timestamps=false

