# Server
server.port=8080

# Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ripple_db
spring.datasource.username=sreejapaluri
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.com.ripple=DEBUG
logging.level.org.springframework=WARN

#Jwt
jwt.secret=mysupersecurejwtsecretkeymysupersecurejwtsecretkey12345
jwt.expiration=86400000


